name: test-build-release
on:
  push:
    branches:
      - master
  pull_request:
env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE: ${{ github.repository }}
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Install bats
        uses: bats-core/bats-action@4.0.0

      - name: Run tests
        run: just test

  release:
    name: Create release
    needs: tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Bump version and push tag
        id: dump-version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          DOCKERHUB_USERNAME=$(echo "${IMAGE}" | awk -F"/" '{print $1}')
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker build -t ${IMAGE}:${{ steps.dump-version.outputs.new_tag }} .
          docker tag ${IMAGE}:${{ steps.dump-version.outputs.new_tag }} ${IMAGE}:latest
          docker push --all-tags ${IMAGE}
